// auto generated by script. Do not modify.

var Error_Internal             = 1;
var Error_DbError              = 2;
var Error_JsonEncodeError      = 3;
var Error_JsonDecodeError      = 4;
var Error_RequestTooFrequently = 5;
var Error_InvalidArgument      = 6;

var ErrorDefine = {
    'Error_Internal':             1,
    'Error_DbError':              2,
    'Error_JsonEncodeError':      3,
    'Error_JsonDecodeError':      4,
    'Error_RequestTooFrequently': 5,
    'Error_InvalidArgument':      6,
};

var Error = {
    1: '内部错误',
    2: '数据库错误',
    3: 'JSON',
    4: 'JSON',
    5: '请求过于频繁',
    6: '参数错误',
};

